### ISSUE TITLE
[Feature Request] Log ignore: filter on command params like URL

### ISSUE THREAD

**Issue by glitsj16** [elesiuta/picosnitch#10]
Hi, I really like the `Log ignore` option. Would it be possible to add `URL's` (or patterns of) to that so users could more easily distinguish between `expected` vs `unexpected` connections?

IMO such a feature would be very useful for filtering connections made by programs like `curl`, `nc`, `ssh`, `wget` and the like.

**Comment by elesiuta** [comment]
I'll look into this and think about the best way to do it, keep in mind though that reverse dns lookups aren't perfect, since the mapping between domains and ips aren't 1:1, and picosnitch doesn't look at the packets to find the actual URL.

**Comment by elesiuta** [comment]
How's this? I may still change it up a bit before next release, but this is what I'm currently learning towards, https://github.com/elesiuta/picosnitch/commit/abdd91f94a85dc962ca8d5f96f8aaea5ed3d599e

**Comment by glitsj16** [comment]
That's working great for me. I like the `startswith` implementation. You're absolutely right that more complicated cases can be dealt with outside of picosnitch via its conn.log. A big thank you!
