### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by lazysoundsystem** [elesiuta/picosnitch#13]
I noticed recently picosnitch running at 100% CPU so I stopped it.

I turned it on again today and noticed the same thing.

Within seconds of starting picosnitch it's running at 100% CPU. I'm not sure if it's related to the recent update, but I'm pretty sure that last week it was working normally.

**Comment by elesiuta** [comment]
I just released 0.10.1 which should fix any regression from 0.10.0, let me know if this works for you.

**Comment by lazysoundsystem** [comment]
Many thanks, it's all better now.

Closing this issue as fixed.
