### ISSUE TITLE
Dashboard bind ip / interface not configurable

### ISSUE THREAD

**Issue by rafaelreis-r** [elesiuta/picosnitch#18]
Hey there. Nifty tool! 

I was not able to access the dashboard though. I'm running it on a headless server, and the dash binds to 127.0.0.1:5100, allowing only local connections. 

Would it be possible to select ip / port in the configuration?

Thanks

**Comment by elesiuta** [comment]
Thanks!

You can configure this by setting the environment variables HOST and PORT (sorry, I forgot to mention this in the docs).
