### ISSUE TITLE
chrome webdriver

### ISSUE THREAD

**Issue by ramyak-mehra** [elesiuta/picosnitch#20]
I was running a script using selnium and wanted to monitor the bandwidth of the spawned chrome instance, but it doest show that inside the filter.

**Comment by elesiuta** [comment]
I assume you're still able to see traffic coming from chrome? What do you see as the parent executable for the traffic? Try selecting Parent Executable where the Executable is chrome.

I've never used selenium so I don't know which executable spawns the chrome instance. Also I see selenium has multiple bindings, which language are you using for your script?

**Comment by ramyak-mehra** [comment]
Yes I was able to solve it, sorry i forgot to close the issue. I am not sure how i fixed it but I vaguely remember that i cleared the sqlite db and then it worked. I could be wrong. Although it had nothing to do with selenium or any other stuff. It just treats everything the same.

**Comment by elesiuta** [comment]
No worries, thanks for letting me know and glad you were able to solve it!
