### ISSUE TITLE
picosnitch not reporting data on void linux (musl libc)

### ISSUE THREAD

**Issue by whatbh** [elesiuta/picosnitch#27]
On void linux (musl libc), picosnitch can show the number of connection, but does not show how much sent/received data (in KB, MB, etc) accumulated.
<img width="641" alt="Screen Shot 2023-02-10 at 7 15 39 PM" src="https://user-images.githubusercontent.com/91888303/218090559-f7541570-5092-43c4-9d5a-90a01aa0ee9e.png">

**Comment by elesiuta** [comment]
Thanks for reporting this, I was able to reproduce it in a VM with the live image.

Running `picosnitch start-no-daemon` let me see that the bpf subprocess kept crashing due to missing kernel headers.

I didn't get a chance to try this since the older headers for the live image's kernel are no longer in the repo.

Let me know if installing the linux headers fixes it for you, and if not, what the output of `picosnitch start-no-daemon` is and I'll dig a little deeper.

**Comment by whatbh** [comment]
I tried to install the package `linux-headers` but after that the problem still persists.
Here is the output of `picosnitch start-no-daemon`
```
starting picosnitch in simple mode
using config and log files from: /home/void/.config/picosnitch
using DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
Process snitchmonitor:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/void/.local/lib/python3.11/site-packages/picosnitch.py", line 968, in monitor_subprocess
    b.attach_uprobe(name="c", sym="getaddrinfo", fn_name="dns_entry")
  File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 1370, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid, sym_off)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 968, in _check_path_symbol
    raise Exception("could not determine address of symbol %s in %s"
Exception: could not determine address of symbol getaddrinfo in c
FD Read Error for {'pid': 737, 'name': 'tor', 'fd': '/proc/16426/fd/34', 'dev': 45826, 'ino': 136673, 'exe': '/usr/bin/tor', 'cmdline': 'tor\x00--quiet\x00--runasdaemon\x000\x00', 'ppid': 711, 'pname': 'runsv', 'pfd': '/proc/16426/fd/19', 'pdev': 45826, 'pino': 136652, 'pexe': '/usr/bin/runsv', 'pcmdline': 'runsv\x00wpa_supplicant\x00', 'uid': 996, 'send': 0, 'recv': 0, 'port': 51462, 'ip': '127.0.0.1', 'domain': ''} (fallback pid hash successful)
picosnitch subprocess died, attempting restart, terminate by running `picosnitch stop`
```

**Comment by elesiuta** [comment]
It looks like the issue is with attaching the uprobe for getaddrinfo. This is only used for getting the domain names used for your connections, and as a fallback picosnitch also does a reverse DNS lookup with python.

I updated picosnitch to catch this exception and rely solely on the fallback if this happens. Since you already have the dependencies installed, no matter how you installed picosnitch, you can test this by simply downloading and running  `picosnitch.py`. If this works and there's no other bugs I'll create a release soon.

I'm not sure, but this may be an upstream issue with bcc, or due to a recent change in the kernel, since I also get this error now with bcc.gethostlatency (but not with gethostlatency-bpfcc, or picosnitch, yet?) which also uses a uprobe for getaddrinfo.

**Comment by whatbh** [comment]
Thank you very much for your quick follow up. I have downloaded and run the updated `picosnitch.py` file. However, this time it still did not show sent/received data. `picosnitch start-no-daemon` came up with another error on my system.

```
starting picosnitch in simple mode
using config and log files from: /home/void/.config/picosnitch
using DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
BPF.attach_uprobe() failed for getaddrinfo, falling back to only using reverse DNS lookup

Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x7fe74be79120>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/bcc/table.py", line 982, in raw_cb_
    callback(cpu, data, size)
  File "/home/void/.local/lib/python3.11/site-packages/picosnitch.py", line 1029, in queue_recvv6_event
    snitch_pipe.send_bytes(pickle.dumps({"pid": pid, "name": event.comm.decode(), "fd": fd, "dev": st_dev, "ino": st_ino, "exe": exe, "cmdline": cmd,
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/.local/lib/python3.11/site-packages/picosnitch.py", line 885, in <lambda>
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
                                                ^^^^^^^^^^^
SystemExit: 0
```

**Comment by elesiuta** [comment]
No problem!

I'm not sure what is causing this next error yet, I installed void (musl) in a VM and unfortunately was not able to reproduce it, and with sent/received data amounts now working under the default settings.

The error is with the [send_bytes](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.connection.Connection.send_bytes) method, is there anything about your system that you think may be relevant and is it up to date? Could you check ~/.config/picosnitch/error.log and try disabling programs which connect to the internet one by one? My best guess is one of them has a very long cmdline which is causing the data to be larger than your pipe buffer size.

**Comment by whatbh** [comment]
I will try out your suggestions but I might not be able to do it in a few days because I'm quite occupied with IRL stuffs. So thank you for this and I think you can close this issue for now. I will keep you posted if I found something on my end.

**Comment by elesiuta** [comment]
No worries, thanks! I modified the code to test whether it was related to the pipe buffer size by adjusting it and artificially increasing the message length, and was unable to trigger this or any error.

I now suspect the BPF callbacks may be happening in parallel/too quickly so I'll try creating a separate pipe for each callback, let me know if this works when you get a chance.

**Comment by whatbh** [comment]
Good news! 
I tried the latest version and it works. `picosnitch` can report the sent/received data now.
Thanks for creating this tool.
<img width="646" alt="Screen Shot 2023-02-18 at 1 48 40 PM" src="https://user-images.githubusercontent.com/91888303/219846014-13d6bf7e-fc67-460c-99d1-a258686b2018.png">

**Comment by elesiuta** [comment]
You're welcome, thanks for finding these issues and helping with debugging!
