### ISSUE TITLE
Errors are being redireceted to /dev/null

### ISSUE THREAD

**Issue by aeonik** [elesiuta/picosnitch#30]
https://github.com/elesiuta/picosnitch/blob/34f9f1f2cad39b6c2725f1f98a2d99fe65b98f1c/picosnitch.py#L2330-L2334

Hello,
Please remove the redirections and pipes to `/dev/null` for errors. You may want to consider removing all `/dev/null` redirections.

I got picosnitch up and running today, but with some difficulty. `picosnitch dash` wasn't starting, and gave no error messages, nor logs.

I had to open up my Python IDE in order to trace the code. I removed these `/dev/null` statements, and eventually found that Arch Linux currently has out of date packages for python-dash, which breaks with newer versions of Flask.

I have submitted changes to the Arch User Repo to get these packages updated, however I would appreciate not hiding these error messages. In case packages get updated and break things in the future, users will be able to troubleshoot what is wrong with their system more easily.

Love your work!

Regards,
Aeonik

**Comment by elesiuta** [comment]
Thank you!

The command `picosnitch dash` is intended to be more "user friendly" and completely detach itself from the terminal, but I agree showing the errors would be helpful. There is also the currently undocumented command `picosnitch start-dash` which does not detach itself nor pipe to /dev/null.

Maybe when dash launches, the below print statement could also suggest trying `start-dash` to see any error messages if dash fails to open.

https://github.com/elesiuta/picosnitch/blob/34f9f1f2cad39b6c2725f1f98a2d99fe65b98f1c/picosnitch.py#L2326-L2330

It is also probably worth mentioning the `DASH_DEBUG` environment variable which enables the [dash dev tools](https://dash.plotly.com/devtools) when true.

The same also goes for `picosnitch start` and `picosnitch start-no-daemon` (but this is already the command systemd uses so you'd see the errors in journalctl).
